"""add is verified and expiry columns

Revision ID: 1066ed34f4e9
Revises: 2f60b085011e
Create Date: 2025-06-16 01:00:55.409754

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1066ed34f4e9"
down_revision: Union[str, None] = "2f60b085011e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("expiry", sa.DateTime(), nullable=False))
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified")
    op.drop_column("notes", "expiry")
    # ### end Alembic commands ###
