"""modify first and last name columns

Revision ID: 1f7ba15de9b8
Revises: d17232a9d50a
Create Date: 2025-06-15 19:09:09.714085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7ba15de9b8'
down_revision: Union[str, None] = 'd17232a9d50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=32), nullable=False))
    op.drop_column('users', 'LastName')
    op.drop_column('users', 'FirstName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('FirstName', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('LastName', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
