"""add first and last names

Revision ID: d17232a9d50a
Revises: 28161c279d04
Create Date: 2025-06-15 18:55:32.509161

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d17232a9d50a"
down_revision: Union[str, None] = "28161c279d04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("FirstName", sa.String(length=32), nullable=False))
    op.add_column("users", sa.Column("LastName", sa.String(length=32), nullable=False))
    op.add_column(
        "users", sa.Column("password_hash", sa.String(length=128), nullable=False)
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "password_hash")
    op.drop_column("users", "LastName")
    op.drop_column("users", "FirstName")
    # ### end Alembic commands ###
